"""initial

Revision ID: 9ada5b01605d
Revises: 
Create Date: 2026-09-30 01:33:06.550263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ada5b01605d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('scope_summary', sa.Text(), nullable=False),
    sa.Column('latest_revision_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('successor_is_code', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'WITHDRAWN', 'REVISED')", name='ck_standards_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('is_code')
    )
    op.create_table('normative_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("relationship_type IN ('TEST_METHOD', 'TERMINOLOGY', 'SAFETY', 'INSTALLATION')", name='ck_normative_relationship'),
    sa.CheckConstraint('parent_id <> child_id', name='ck_normative_no_self'),
    sa.ForeignKeyConstraint(['child_id'], ['standards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', 'relationship_type', name='uq_normative_edge')
    )
    op.create_table('quality_control_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('standard_id', sa.UUID(), nullable=False),
    sa.Column('qco_title', sa.String(length=300), nullable=False),
    sa.Column('issuing_ministry', sa.String(length=200), nullable=False),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('notification_ref', sa.String(length=400), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('certification_scheme', sa.String(length=20), nullable=False),
    sa.Column('evidence_level', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(evidence_level = 'cited' AND notification_ref <> '' AND source_url <> '') OR evidence_level = 'unverified'", name='ck_qco_cited_has_source'),
    sa.CheckConstraint("certification_scheme IN ('ISI', 'CRS', 'HALLMARK', 'NONE')", name='ck_qco_scheme'),
    sa.CheckConstraint("evidence_level <> 'unverified' OR is_mandatory = false", name='ck_qco_unverified_not_mandatory'),
    sa.CheckConstraint("evidence_level IN ('cited', 'unverified')", name='ck_qco_evidence'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_control_orders')
    op.drop_table('normative_references')
    op.drop_table('standards')
    # ### end Alembic commands ###
